name: Deploy Docsify to GitHub Pages

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 使用 Node.js 16

      - name: Install docsify-cli
        run: npm install -g docsify-cli

      - name: Build Docsify site
        run: docsify init ./docs # 如果已經初始化過可以跳過這一步

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Docsify 文件夾

